apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-config.yaml
  - prometheus.yaml
  - grafana.yaml
  - grafana-dashboards.yaml
  - test-metrics-exporter.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: fastfood-monitoring
  app.kubernetes.io/managed-by: kustomize
