{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastfood.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "fastfood.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  MONGODB_PASSWORD: {{ .Values.secrets.mongodbPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
{{- end }}
