{{- range $serviceName, $service := dict "authService" .Values.authService "orderService" .Values.orderService "restaurantService" .Values.restaurantService "paymentService" .Values.paymentService "notificationService" .Values.notificationService "adminService" .Values.adminService }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "fastfood.labels" $ | nindent 4 }}
    app: {{ $service.name }}
spec:
  type: {{ $service.service.type }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: {{ $service.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ $service.name }}
{{- end }}
{{- end }}
